name: WtsWtbPlugin
version: 1.1
api-version: 1.13
main: id.fakhrads.spigotmc.plugin.template.WtsWtbPlugin

commands:
  wts:
    description: Broadcast WTS announcement
  wtb:
    description: Broadcast WTB announcement
